name: smart_sight
description: An app to manipulate images
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  color: ^3.0.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flython: ^0.2.0
  go_router: ^10.1.2
  image: ^4.1.3
  image_picker: ^1.0.4
  macos_ui: any
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
